name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hw-folder: [hw1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        if [ -f ${{ matrix.hw-folder }}/requirements.txt ]; then pip install -r ${{ matrix.hw-folder }}/requirements.txt; fi

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest ${{ matrix.hw-folder }}/tests.py